"""Seed data for SciAi-Nova OS platform."""

AGENTS = [
    # Target Discovery
    {"name": "Pathway Insight Agent", "category": "Target Discovery", "value_chain_stage": "Target Discovery",
     "description": "Analyzes biological pathways to identify druggable nodes and cascade effects.",
     "input_types": ["pathway_id", "gene_list"], "output_types": ["pathway_map", "druggable_nodes"],
     "tools_used": ["KEGG", "Reactome", "KG Query"], "model_used": "gpt-4o", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Target Hypothesis Generation Agent", "category": "Target Discovery", "value_chain_stage": "Target Discovery",
     "description": "Generates ranked target hypotheses from literature and omics evidence.",
     "input_types": ["disease", "omics_data"], "output_types": ["hypothesis_list", "evidence_bundle"],
     "tools_used": ["Literature Miner", "KG Builder"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "medium", "human_approval_required": True},
    {"name": "Evidence Scout Agent", "category": "Target Discovery", "value_chain_stage": "Target Discovery",
     "description": "Scouts and aggregates evidence from papers, patents, and clinical databases.",
     "input_types": ["target_name", "disease"], "output_types": ["evidence_report", "citations"],
     "tools_used": ["PubMed", "Patent DB", "Vector Search"], "model_used": "literature-intelligence-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Target Validation Agent", "category": "Target Discovery", "value_chain_stage": "Target Discovery",
     "description": "Validates target-disease associations using multi-source evidence scoring.",
     "input_types": ["target_id", "evidence_bundle"], "output_types": ["validation_score", "gap_analysis"],
     "tools_used": ["KG Query", "Ontology Mapper"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "high", "human_approval_required": True},
    {"name": "Biomarker Discovery Agent", "category": "Target Discovery", "value_chain_stage": "Target Discovery",
     "description": "Identifies candidate biomarkers from omics and clinical datasets.",
     "input_types": ["omics_dataset", "cohort_metadata"], "output_types": ["biomarker_candidates", "statistical_report"],
     "tools_used": ["Bioinformatics Pipeline", "Data Profiler"], "model_used": "bioinformatics-slm", "slm_eligible": True, "risk_level": "medium", "human_approval_required": False},
    {"name": "Druggability Finder Agent", "category": "Target Discovery", "value_chain_stage": "Target Discovery",
     "description": "Assesses target druggability using structural and ligandability data.",
     "input_types": ["protein_id", "structure_data"], "output_types": ["druggability_score", "binding_site_analysis"],
     "tools_used": ["PDB Query", "ChEMBL"], "model_used": "molecular-intelligence-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    # Lead Identification
    {"name": "Molecule Generation Agent", "category": "Lead Identification", "value_chain_stage": "Lead Identification",
     "description": "Generates novel molecular structures based on target pharmacophore constraints.",
     "input_types": ["target_structure", "scaffold"], "output_types": ["molecule_list", "SMILES"],
     "tools_used": ["RDKit", "Generative Model"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "medium", "human_approval_required": True},
    {"name": "Virtual Screening Agent", "category": "Lead Identification", "value_chain_stage": "Lead Identification",
     "description": "Performs virtual screening against compound libraries.",
     "input_types": ["target_structure", "compound_library"], "output_types": ["hit_list", "docking_scores"],
     "tools_used": ["AutoDock", "Compound DB"], "model_used": "molecular-intelligence-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "MPO Scoring Agent", "category": "Lead Identification", "value_chain_stage": "Lead Identification",
     "description": "Multi-parameter optimization scoring for lead compounds.",
     "input_types": ["compound_list"], "output_types": ["mpo_scores", "radar_chart_data"],
     "tools_used": ["RDKit", "ADMET Predictor"], "model_used": "molecular-intelligence-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Assay Design Agent", "category": "Lead Identification", "value_chain_stage": "Lead Identification",
     "description": "Designs biochemical and cell-based assays for hit validation.",
     "input_types": ["target_info", "compound_list"], "output_types": ["assay_protocol", "controls"],
     "tools_used": ["Protocol DB", "Literature Miner"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "medium", "human_approval_required": True},
    {"name": "Deduplication, Filtering & Hit-Ranking Agent", "category": "Lead Identification", "value_chain_stage": "Lead Identification",
     "description": "Deduplicates, filters, and ranks screening hits by multi-criteria scoring.",
     "input_types": ["hit_list", "filters"], "output_types": ["ranked_hits", "filter_report"],
     "tools_used": ["RDKit", "Data Profiler"], "model_used": "molecular-intelligence-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Early Risk Profiling Agent", "category": "Lead Identification", "value_chain_stage": "Lead Identification",
     "description": "Profiles early-stage compounds for toxicity and off-target risks.",
     "input_types": ["compound_list"], "output_types": ["risk_profile", "alerts"],
     "tools_used": ["ToxPredict", "Off-Target DB"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "high", "human_approval_required": True},
    # Lead Optimization
    {"name": "Multitarget QSAR Agent", "category": "Lead Optimization", "value_chain_stage": "Lead Optimization",
     "description": "Builds QSAR models across multiple biological targets.",
     "input_types": ["training_data", "target_list"], "output_types": ["qsar_models", "predictions"],
     "tools_used": ["Scikit-learn", "RDKit"], "model_used": "molecular-intelligence-slm", "slm_eligible": True, "risk_level": "medium", "human_approval_required": False},
    {"name": "Selectivity & Mechanism Agent", "category": "Lead Optimization", "value_chain_stage": "Lead Optimization",
     "description": "Analyzes compound selectivity profiles and mechanism of action.",
     "input_types": ["compound_id", "panel_data"], "output_types": ["selectivity_matrix", "moa_hypothesis"],
     "tools_used": ["KG Query", "Pathway Analysis"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "medium", "human_approval_required": True},
    {"name": "ADMET Prediction Agent", "category": "Lead Optimization", "value_chain_stage": "Lead Optimization",
     "description": "Predicts ADMET properties for lead optimization candidates.",
     "input_types": ["compound_list"], "output_types": ["admet_predictions", "property_radar"],
     "tools_used": ["ADMET Model", "RDKit"], "model_used": "molecular-intelligence-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Explainable ADMET Agent", "category": "Lead Optimization", "value_chain_stage": "Lead Optimization",
     "description": "Provides explainable ADMET predictions with structural alerts.",
     "input_types": ["compound_id"], "output_types": ["admet_explanation", "structural_alerts"],
     "tools_used": ["SHAP", "ADMET Model"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "medium", "human_approval_required": False},
    {"name": "Off-Target Risk Prediction Agent", "category": "Lead Optimization", "value_chain_stage": "Lead Optimization",
     "description": "Predicts off-target binding risks across the proteome.",
     "input_types": ["compound_list"], "output_types": ["off_target_risks", "risk_heatmap"],
     "tools_used": ["SEA", "Off-Target DB"], "model_used": "molecular-intelligence-slm", "slm_eligible": True, "risk_level": "high", "human_approval_required": True},
    {"name": "Developability Scoring Agent", "category": "Lead Optimization", "value_chain_stage": "Lead Optimization",
     "description": "Scores compounds on developability criteria for candidate selection.",
     "input_types": ["compound_list"], "output_types": ["developability_scores", "recommendations"],
     "tools_used": ["Property Calculator", "Rule Engine"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "medium", "human_approval_required": True},
    # Preclinical
    {"name": "In-vivo Study Design Agent", "category": "Preclinical", "value_chain_stage": "Preclinical Studies",
     "description": "Designs in-vivo efficacy and safety study protocols.",
     "input_types": ["compound_id", "indication"], "output_types": ["study_protocol", "power_analysis"],
     "tools_used": ["Protocol DB", "Statistical Planner"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "high", "human_approval_required": True},
    {"name": "Efficacy Modelling Agent", "category": "Preclinical", "value_chain_stage": "Preclinical Studies",
     "description": "Models dose-response and efficacy outcomes from preclinical data.",
     "input_types": ["study_data"], "output_types": ["efficacy_model", "dose_recommendation"],
     "tools_used": ["PK/PD Model", "Plot Generator"], "model_used": "bioinformatics-slm", "slm_eligible": True, "risk_level": "medium", "human_approval_required": False},
    {"name": "PK/PD Modelling Agent", "category": "Preclinical", "value_chain_stage": "Preclinical Studies",
     "description": "Builds pharmacokinetic and pharmacodynamic models.",
     "input_types": ["pk_data", "pd_data"], "output_types": ["pkpd_model", "simulation_results"],
     "tools_used": ["NONMEM", "Plot Generator"], "model_used": "bioinformatics-slm", "slm_eligible": True, "risk_level": "medium", "human_approval_required": True},
    {"name": "Toxicity Prediction Agent", "category": "Preclinical", "value_chain_stage": "Preclinical Studies",
     "description": "Predicts organ toxicity and safety liabilities.",
     "input_types": ["compound_id", "study_data"], "output_types": ["toxicity_profile", "risk_flags"],
     "tools_used": ["ToxPredict", "Literature Miner"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "high", "human_approval_required": True},
    {"name": "Formulation Strategy Agent", "category": "Preclinical", "value_chain_stage": "Preclinical Studies",
     "description": "Recommends formulation strategies for preclinical dosing.",
     "input_types": ["compound_properties"], "output_types": ["formulation_options", "stability_notes"],
     "tools_used": ["Formulation DB", "Property Calculator"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "medium", "human_approval_required": False},
    {"name": "Translational Package Assembly Agent", "category": "Preclinical", "value_chain_stage": "Preclinical Studies",
     "description": "Assembles translational research packages for IND-enabling studies.",
     "input_types": ["study_results", "compound_data"], "output_types": ["translational_package", "gap_analysis"],
     "tools_used": ["Report Generator", "Compliance Checker"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "high", "human_approval_required": True},
    # Early Development & CMC
    {"name": "Analytical Characterization Agent", "category": "Early Development & CMC", "value_chain_stage": "Early Development & CMC",
     "description": "Plans analytical characterization methods for drug substance and product.",
     "input_types": ["compound_id", "formulation"], "output_types": ["analytical_plan", "method_list"],
     "tools_used": ["Method DB", "Compliance Checker"], "model_used": "compliance-gxp-slm", "slm_eligible": True, "risk_level": "medium", "human_approval_required": True},
    {"name": "Formulation Optimisation Agent", "category": "Early Development & CMC", "value_chain_stage": "Early Development & CMC",
     "description": "Optimizes formulation parameters for stability and bioavailability.",
     "input_types": ["formulation_data"], "output_types": ["optimized_formulation", "DOE_results"],
     "tools_used": ["DOE Designer", "Stability Model"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "medium", "human_approval_required": True},
    {"name": "Process Design and Scale-up Agent", "category": "Early Development & CMC", "value_chain_stage": "Early Development & CMC",
     "description": "Designs manufacturing processes and scale-up strategies.",
     "input_types": ["synthesis_route", "batch_data"], "output_types": ["process_design", "scale_up_plan"],
     "tools_used": ["Process DB", "QbD Framework"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "high", "human_approval_required": True},
    {"name": "Manufacturing Planning Agent", "category": "Early Development & CMC", "value_chain_stage": "Early Development & CMC",
     "description": "Plans manufacturing schedules and resource allocation.",
     "input_types": ["process_design", "demand_forecast"], "output_types": ["manufacturing_plan", "timeline"],
     "tools_used": ["Scheduler", "Inventory Manager"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "medium", "human_approval_required": True},
    {"name": "Stability Prediction Agent", "category": "Early Development & CMC", "value_chain_stage": "Early Development & CMC",
     "description": "Predicts product stability under various storage conditions.",
     "input_types": ["formulation_data", "stability_data"], "output_types": ["stability_prediction", "shelf_life"],
     "tools_used": ["Stability Model", "Plot Generator"], "model_used": "molecular-intelligence-slm", "slm_eligible": True, "risk_level": "medium", "human_approval_required": False},
    {"name": "Quality by Design Agent", "category": "Early Development & CMC", "value_chain_stage": "Early Development & CMC",
     "description": "Implements QbD framework for process and product quality.",
     "input_types": ["process_data", "CQAs"], "output_types": ["qbd_document", "design_space"],
     "tools_used": ["QbD Framework", "Compliance Checker"], "model_used": "compliance-gxp-slm", "slm_eligible": True, "risk_level": "high", "human_approval_required": True},
    # Cross-Functional
    {"name": "Literature/Patent Miner", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Mines scientific literature and patents for relevant insights.",
     "input_types": ["query", "date_range"], "output_types": ["mined_documents", "summary"],
     "tools_used": ["PubMed", "Patent DB", "Vector Search"], "model_used": "literature-intelligence-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Semantic Q&A Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Answers scientific questions using RAG over knowledge base.",
     "input_types": ["question"], "output_types": ["answer", "citations"],
     "tools_used": ["Vector Search", "KG Query"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "low", "human_approval_required": False},
    {"name": "Ontology Mapper Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Maps extracted entities to standard biomedical ontologies.",
     "input_types": ["entity_list"], "output_types": ["mapped_entities", "confidence_scores"],
     "tools_used": ["UMLS", "GO", "ChEBI"], "model_used": "ontology-mapping-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Knowledge Scout Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Scouts knowledge graph for relevant connections and gaps.",
     "input_types": ["entity_id", "depth"], "output_types": ["knowledge_map", "gaps"],
     "tools_used": ["KG Query", "Vector Search"], "model_used": "literature-intelligence-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Hypothesis Validation Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Validates scientific hypotheses against available evidence.",
     "input_types": ["hypothesis"], "output_types": ["validation_report", "evidence_for_against"],
     "tools_used": ["KG Query", "Literature Miner"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "medium", "human_approval_required": True},
    {"name": "Hypothesis Builder Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Builds structured scientific hypotheses from evidence.",
     "input_types": ["evidence_bundle"], "output_types": ["hypothesis", "supporting_evidence"],
     "tools_used": ["KG Builder", "Literature Miner"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "medium", "human_approval_required": True},
    {"name": "Competitive Intel Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Analyzes competitive landscape from patents and clinical trials.",
     "input_types": ["therapeutic_area", "target"], "output_types": ["competitive_landscape", "pipeline_analysis"],
     "tools_used": ["Patent DB", "ClinicalTrials.gov"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "medium", "human_approval_required": False},
    {"name": "ELN/LIMS Copilot Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Assists with ELN and LIMS data entry and retrieval.",
     "input_types": ["experiment_id", "query"], "output_types": ["eln_data", "suggestions"],
     "tools_used": ["ELN Connector", "LIMS Connector"], "model_used": "gpt-4o", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Experiment Planner Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Plans experiments with resource and timeline optimization.",
     "input_types": ["hypothesis", "constraints"], "output_types": ["experiment_plan", "timeline"],
     "tools_used": ["Scheduler", "Inventory Manager"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "medium", "human_approval_required": True},
    {"name": "DOE Designer Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Designs design-of-experiments matrices for optimization studies.",
     "input_types": ["factors", "responses"], "output_types": ["doe_matrix", "power_analysis"],
     "tools_used": ["DOE Engine", "Statistical Planner"], "model_used": "bioinformatics-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Scheduler Ops Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Manages lab scheduling and resource allocation.",
     "input_types": ["experiments", "resources"], "output_types": ["schedule", "conflicts"],
     "tools_used": ["Scheduler"], "model_used": "gpt-4o", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Sample Tracker Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Tracks biological and chemical samples across studies.",
     "input_types": ["sample_id"], "output_types": ["sample_lineage", "location"],
     "tools_used": ["LIMS Connector", "Barcode Scanner"], "model_used": "gpt-4o", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Inventory Manager Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Manages reagent and compound inventory levels.",
     "input_types": ["inventory_query"], "output_types": ["inventory_status", "reorder_alerts"],
     "tools_used": ["Inventory DB"], "model_used": "gpt-4o", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Omics Ingestion Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Ingests and normalizes omics datasets into the data fabric.",
     "input_types": ["omics_files"], "output_types": ["normalized_data", "qc_report"],
     "tools_used": ["Data Profiler", "Bioinformatics Pipeline"], "model_used": "bioinformatics-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Bioinformatics Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Runs bioinformatics analyses on genomic and proteomic data.",
     "input_types": ["analysis_type", "data"], "output_types": ["analysis_results", "visualizations"],
     "tools_used": ["Bioinformatics Pipeline", "Plot Generator"], "model_used": "bioinformatics-slm", "slm_eligible": True, "risk_level": "medium", "human_approval_required": False},
    {"name": "Decision Capture Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Captures and documents scientific decisions with rationale.",
     "input_types": ["decision_context"], "output_types": ["decision_record", "audit_trail"],
     "tools_used": ["Audit Logger"], "model_used": "scientific-writing-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "NGS Data Quality Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Assesses quality of next-generation sequencing data.",
     "input_types": ["ngs_files"], "output_types": ["qc_metrics", "pass_fail"],
     "tools_used": ["FastQC", "Data Profiler"], "model_used": "bioinformatics-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Traceability Management Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Manages end-to-end traceability of data and samples.",
     "input_types": ["entity_id"], "output_types": ["traceability_chain", "provenance"],
     "tools_used": ["Audit Logger", "KG Query"], "model_used": "compliance-gxp-slm", "slm_eligible": True, "risk_level": "medium", "human_approval_required": False},
    {"name": "Model Ops Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Monitors and manages deployed ML models in production.",
     "input_types": ["model_id"], "output_types": ["model_health", "drift_report"],
     "tools_used": ["Model Monitor", "Drift Detector"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "medium", "human_approval_required": True},
    {"name": "Synthetic Data Generator", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Generates synthetic datasets for model training and testing.",
     "input_types": ["schema", "row_count"], "output_types": ["synthetic_dataset", "quality_report"],
     "tools_used": ["Data Generator"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "low", "human_approval_required": False},
    {"name": "Data Governance Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Enforces data governance policies and lineage tracking.",
     "input_types": ["dataset_id"], "output_types": ["governance_report", "policy_violations"],
     "tools_used": ["Audit Logger", "Policy Engine"], "model_used": "compliance-gxp-slm", "slm_eligible": True, "risk_level": "high", "human_approval_required": True},
    {"name": "Study Report Generator", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Generates structured study reports from experimental data.",
     "input_types": ["study_data"], "output_types": ["study_report", "figures"],
     "tools_used": ["Report Generator", "Plot Generator"], "model_used": "scientific-writing-slm", "slm_eligible": True, "risk_level": "medium", "human_approval_required": True},
    {"name": "Scientific Writer Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Assists with scientific writing for publications and reports.",
     "input_types": ["content_outline", "data"], "output_types": ["draft_document", "references"],
     "tools_used": ["Literature Miner", "Citation Manager"], "model_used": "scientific-writing-slm", "slm_eligible": True, "risk_level": "medium", "human_approval_required": True},
    {"name": "Privacy Guard Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Detects and redacts personally identifiable information in datasets.",
     "input_types": ["document"], "output_types": ["redacted_document", "pii_report"],
     "tools_used": ["PII Detector"], "model_used": "compliance-gxp-slm", "slm_eligible": True, "risk_level": "high", "human_approval_required": True},
    {"name": "IP Landscape Screener", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Screens intellectual property landscape for freedom-to-operate.",
     "input_types": ["compound_structure", "therapeutic_area"], "output_types": ["ip_landscape", "fto_assessment"],
     "tools_used": ["Patent DB", "Structure Search"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "high", "human_approval_required": True},
    {"name": "GxP Compliance Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Checks documents and processes for GxP compliance.",
     "input_types": ["document", "process_type"], "output_types": ["compliance_report", "findings"],
     "tools_used": ["Compliance Checker", "Audit Logger"], "model_used": "compliance-gxp-slm", "slm_eligible": True, "risk_level": "high", "human_approval_required": True},
    {"name": "Contract Review Assistant", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Reviews CRO/CDMO contracts for scientific and compliance terms.",
     "input_types": ["contract_document"], "output_types": ["review_summary", "risk_items"],
     "tools_used": ["Document Parser", "Compliance Checker"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "high", "human_approval_required": True},
    {"name": "AI Risk Assessor", "category": "Cross-Functional", "value_chain_stage": "Cross-Functional",
     "description": "Assesses AI/ML model risks for regulatory and ethical compliance.",
     "input_types": ["model_metadata"], "output_types": ["risk_assessment", "mitigation_plan"],
     "tools_used": ["Risk Engine", "Audit Logger"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "high", "human_approval_required": True},
    # Foundation
    {"name": "Web Search Agent", "category": "Foundation", "value_chain_stage": "Foundation",
     "description": "Searches the web for scientific information and news.",
     "input_types": ["query"], "output_types": ["search_results", "summaries"],
     "tools_used": ["Web Search API"], "model_used": "gpt-4o-mini", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Paper Summarizer Agent", "category": "Foundation", "value_chain_stage": "Foundation",
     "description": "Summarizes research papers with key findings extraction.",
     "input_types": ["paper_pdf"], "output_types": ["summary", "key_findings"],
     "tools_used": ["Document Parser", "Vector Search"], "model_used": "literature-intelligence-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Scientific DB Query Agent", "category": "Foundation", "value_chain_stage": "Foundation",
     "description": "Queries external scientific databases (PubChem, UniProt, etc.).",
     "input_types": ["db_query"], "output_types": ["query_results"],
     "tools_used": ["PubChem", "UniProt", "ChEMBL"], "model_used": "gpt-4o-mini", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Document Parser Agent", "category": "Foundation", "value_chain_stage": "Foundation",
     "description": "Parses and extracts structured content from scientific documents.",
     "input_types": ["document_file"], "output_types": ["parsed_content", "metadata"],
     "tools_used": ["PDF Parser", "OCR"], "model_used": "literature-intelligence-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "KG Builder Agent", "category": "Foundation", "value_chain_stage": "Foundation",
     "description": "Builds knowledge graph nodes and relationships from extracted entities.",
     "input_types": ["entities", "relationships"], "output_types": ["graph_update", "stats"],
     "tools_used": ["Neo4j", "Entity Resolver"], "model_used": "ontology-mapping-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Relationship Identifier Agent", "category": "Foundation", "value_chain_stage": "Foundation",
     "description": "Identifies relationships between scientific entities in text.",
     "input_types": ["text", "entities"], "output_types": ["relationships", "confidence_scores"],
     "tools_used": ["NLP Pipeline", "KG Query"], "model_used": "ontology-mapping-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Entity Resolver Agent", "category": "Foundation", "value_chain_stage": "Foundation",
     "description": "Resolves entity mentions to canonical identifiers.",
     "input_types": ["entity_mentions"], "output_types": ["resolved_entities", "disambiguation"],
     "tools_used": ["UMLS", "Entity DB"], "model_used": "ontology-mapping-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Schema Mapper Agent", "category": "Foundation", "value_chain_stage": "Foundation",
     "description": "Maps data schemas between different scientific data formats.",
     "input_types": ["source_schema", "target_schema"], "output_types": ["mapping_rules", "transformed_sample"],
     "tools_used": ["Schema Engine"], "model_used": "gpt-4o-mini", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Model Evaluator Agent", "category": "Foundation", "value_chain_stage": "Foundation",
     "description": "Evaluates ML model performance against benchmarks.",
     "input_types": ["model_id", "test_data"], "output_types": ["evaluation_metrics", "comparison"],
     "tools_used": ["Model Monitor"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "medium", "human_approval_required": False},
    {"name": "Feature Engineer Agent", "category": "Foundation", "value_chain_stage": "Foundation",
     "description": "Engineers molecular and biological features for ML models.",
     "input_types": ["compound_list", "feature_types"], "output_types": ["feature_matrix", "descriptors"],
     "tools_used": ["RDKit", "Bioinformatics Pipeline"], "model_used": "molecular-intelligence-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Model Tuner Agent", "category": "Foundation", "value_chain_stage": "Foundation",
     "description": "Tunes hyperparameters for ML models.",
     "input_types": ["model_config", "training_data"], "output_types": ["tuned_model", "metrics"],
     "tools_used": ["Optuna", "Model Monitor"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "medium", "human_approval_required": True},
    {"name": "Drift/Bias Monitor Agent", "category": "Foundation", "value_chain_stage": "Foundation",
     "description": "Monitors model drift and bias in production deployments.",
     "input_types": ["model_id", "production_data"], "output_types": ["drift_report", "bias_metrics"],
     "tools_used": ["Drift Detector", "Bias Analyzer"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "medium", "human_approval_required": True},
    {"name": "Image Segmenter Agent", "category": "Foundation", "value_chain_stage": "Foundation",
     "description": "Segments microscopy and histology images.",
     "input_types": ["image_file"], "output_types": ["segmentation_mask", "cell_counts"],
     "tools_used": ["CV Pipeline"], "model_used": "bioinformatics-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Data Profiler/Validator", "category": "Foundation", "value_chain_stage": "Foundation",
     "description": "Profiles and validates scientific datasets for quality.",
     "input_types": ["dataset"], "output_types": ["profile_report", "validation_errors"],
     "tools_used": ["Data Profiler"], "model_used": "bioinformatics-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Plot/Graph Generator", "category": "Foundation", "value_chain_stage": "Foundation",
     "description": "Generates publication-quality plots and graphs.",
     "input_types": ["data", "plot_type"], "output_types": ["plot_image", "plot_config"],
     "tools_used": ["Matplotlib", "Plotly"], "model_used": "gpt-4o-mini", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Result Capture Agent", "category": "Foundation", "value_chain_stage": "Foundation",
     "description": "Captures and structures experimental results.",
     "input_types": ["raw_results"], "output_types": ["structured_results", "metadata"],
     "tools_used": ["ELN Connector", "Data Profiler"], "model_used": "scientific-writing-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Workflow Orchestrator", "category": "Foundation", "value_chain_stage": "Foundation",
     "description": "Orchestrates multi-agent workflow execution.",
     "input_types": ["workflow_definition"], "output_types": ["execution_status", "results"],
     "tools_used": ["Agent Router", "Audit Logger"], "model_used": "gpt-4o", "slm_eligible": False, "risk_level": "medium", "human_approval_required": False},
    {"name": "Tool Selection Router", "category": "Foundation", "value_chain_stage": "Foundation",
     "description": "Routes tasks to appropriate tools and agents.",
     "input_types": ["task_description"], "output_types": ["selected_tools", "routing_plan"],
     "tools_used": ["Agent Registry"], "model_used": "gpt-4o-mini", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Notification/Alert Agent", "category": "Foundation", "value_chain_stage": "Foundation",
     "description": "Sends notifications and alerts for platform events.",
     "input_types": ["event", "recipients"], "output_types": ["notification_status"],
     "tools_used": ["Notification Service"], "model_used": "gpt-4o-mini", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
    {"name": "Table/Figure Generator", "category": "Foundation", "value_chain_stage": "Foundation",
     "description": "Generates formatted tables and figures for reports.",
     "input_types": ["data", "format"], "output_types": ["table", "figure"],
     "tools_used": ["Report Generator"], "model_used": "scientific-writing-slm", "slm_eligible": True, "risk_level": "low", "human_approval_required": False},
]

SLM_PROFILES = [
    {"name": "Literature Intelligence SLM", "model_name": "ministral-8b-latest", "model_type": "causal_lm",
     "task_scope": "Paper summarization, citation extraction, literature mining (Ministral 8B)", "fine_tuning_dataset": "pharma_literature_corpus_v2",
     "token_cost_estimate": 0.002, "latency_estimate_ms": 450, "accuracy_score": 0.91, "evaluation_status": "passed",
     "deployment_status": "active", "fallback_model": "gpt-4o-mini",
     "allowed_agents": ["Literature/Patent Miner", "Paper Summarizer Agent", "Evidence Scout Agent", "Knowledge Scout Assistant"]},
    {"name": "Ontology Mapping SLM", "model_name": "ministral-8b-latest", "model_type": "encoder_decoder",
     "task_scope": "Entity resolution, ontology mapping, relationship extraction (Ministral 8B)", "fine_tuning_dataset": "biomedical_ontology_pairs_v1",
     "token_cost_estimate": 0.001, "latency_estimate_ms": 320, "accuracy_score": 0.88, "evaluation_status": "passed",
     "deployment_status": "active", "fallback_model": "gpt-4o-mini",
     "allowed_agents": ["Ontology Mapper Assistant", "KG Builder Agent", "Entity Resolver Agent", "Relationship Identifier Agent"]},
    {"name": "Scientific Writing SLM", "model_name": "ministral-8b-latest", "model_type": "causal_lm",
     "task_scope": "Report generation, scientific writing, decision capture (Ministral 8B)", "fine_tuning_dataset": "pharma_reports_corpus_v1",
     "token_cost_estimate": 0.003, "latency_estimate_ms": 580, "accuracy_score": 0.89, "evaluation_status": "passed",
     "deployment_status": "active", "fallback_model": "gpt-4o",
     "allowed_agents": ["Scientific Writer Assistant", "Study Report Generator", "Decision Capture Assistant", "Result Capture Agent"]},
    {"name": "Compliance/GxP SLM", "model_name": "ministral-8b-latest", "model_type": "causal_lm",
     "task_scope": "GxP compliance checking, audit trail, privacy guard (Ministral 8B)", "fine_tuning_dataset": "gxp_regulatory_corpus_v1",
     "token_cost_estimate": 0.002, "latency_estimate_ms": 400, "accuracy_score": 0.93, "evaluation_status": "passed",
     "deployment_status": "active", "fallback_model": "gpt-4o",
     "allowed_agents": ["GxP Compliance Assistant", "Privacy Guard Assistant", "Data Governance Assistant", "Traceability Management Assistant"]},
    {"name": "Bioinformatics SLM", "model_name": "ministral-8b-latest", "model_type": "causal_lm",
     "task_scope": "Omics analysis, NGS QC, bioinformatics pipelines (Ministral 8B)", "fine_tuning_dataset": "omics_analysis_corpus_v1",
     "token_cost_estimate": 0.002, "latency_estimate_ms": 520, "accuracy_score": 0.87, "evaluation_status": "in_progress",
     "deployment_status": "staging", "fallback_model": "gpt-4o",
     "allowed_agents": ["Bioinformatics Assistant", "Omics Ingestion Assistant", "NGS Data Quality Assistant", "Efficacy Modelling Agent"]},
    {"name": "Molecular Intelligence SLM", "model_name": "ministral-8b-latest", "model_type": "causal_lm",
     "task_scope": "ADMET prediction, virtual screening, molecular property calculation (Ministral 8B)", "fine_tuning_dataset": "chembl_admet_corpus_v2",
     "token_cost_estimate": 0.001, "latency_estimate_ms": 380, "accuracy_score": 0.90, "evaluation_status": "passed",
     "deployment_status": "active", "fallback_model": "gpt-4o-mini",
     "allowed_agents": ["ADMET Prediction Agent", "Virtual Screening Agent", "MPO Scoring Agent", "Druggability Finder Agent"]},
]

WORKFLOW_TEMPLATES = [
    {"name": "Literature to Hypothesis", "description": "End-to-end workflow from literature mining to validated hypothesis generation.",
     "value_chain_stage": "Target Discovery",
     "steps_json": [
         {"agent": "Literature/Patent Miner", "order": 1, "requires_approval": False},
         {"agent": "Knowledge Scout Assistant", "order": 2, "requires_approval": False},
         {"agent": "Ontology Mapper Assistant", "order": 3, "requires_approval": False},
         {"agent": "KG Builder Agent", "order": 4, "requires_approval": False},
         {"agent": "Hypothesis Builder Assistant", "order": 5, "requires_approval": True},
         {"agent": "Hypothesis Validation Assistant", "order": 6, "requires_approval": True},
         {"agent": "Scientific Writer Assistant", "order": 7, "requires_approval": False},
     ]},
    {"name": "Target Discovery", "description": "Comprehensive target discovery pipeline with validation.",
     "value_chain_stage": "Target Discovery",
     "steps_json": [
         {"agent": "Pathway Insight Agent", "order": 1, "requires_approval": False},
         {"agent": "Evidence Scout Agent", "order": 2, "requires_approval": False},
         {"agent": "Biomarker Discovery Agent", "order": 3, "requires_approval": False},
         {"agent": "Target Validation Agent", "order": 4, "requires_approval": True},
         {"agent": "Druggability Finder Agent", "order": 5, "requires_approval": False},
     ]},
    {"name": "Experiment Planning", "description": "Plan and schedule experiments with DOE and resource management.",
     "value_chain_stage": "Cross-Functional",
     "steps_json": [
         {"agent": "Hypothesis Validation Assistant", "order": 1, "requires_approval": False},
         {"agent": "Experiment Planner Assistant", "order": 2, "requires_approval": True},
         {"agent": "DOE Designer Assistant", "order": 3, "requires_approval": False},
         {"agent": "Scheduler Ops Assistant", "order": 4, "requires_approval": False},
         {"agent": "Inventory Manager Assistant", "order": 5, "requires_approval": False},
         {"agent": "ELN/LIMS Copilot Assistant", "order": 6, "requires_approval": False},
     ]},
    {"name": "Study Report Generation", "description": "Generate GxP-compliant study reports from experimental data.",
     "value_chain_stage": "Preclinical Studies",
     "steps_json": [
         {"agent": "Result Capture Agent", "order": 1, "requires_approval": False},
         {"agent": "Data Profiler/Validator", "order": 2, "requires_approval": False},
         {"agent": "Plot/Graph Generator", "order": 3, "requires_approval": False},
         {"agent": "Study Report Generator", "order": 4, "requires_approval": True},
         {"agent": "Scientific Writer Assistant", "order": 5, "requires_approval": True},
         {"agent": "GxP Compliance Assistant", "order": 6, "requires_approval": True},
     ]},
    {"name": "CMC Readiness", "description": "Assess and prepare CMC readiness for early development.",
     "value_chain_stage": "Early Development & CMC",
     "steps_json": [
         {"agent": "Formulation Optimisation Agent", "order": 1, "requires_approval": True},
         {"agent": "Analytical Characterization Agent", "order": 2, "requires_approval": False},
         {"agent": "Process Design and Scale-up Agent", "order": 3, "requires_approval": True},
         {"agent": "Manufacturing Planning Agent", "order": 4, "requires_approval": False},
         {"agent": "Quality by Design Agent", "order": 5, "requires_approval": True},
         {"agent": "Stability Prediction Agent", "order": 6, "requires_approval": False},
     ]},
]

DOCUMENT_TITLES = [
    ("JAK1 inhibitor efficacy in rheumatoid arthritis Phase II study", "study_report", "PDF"),
    ("Compound SN-2847 ADMET profiling results Q3 2025", "assay_dataset", "XLSX"),
    ("Patent US11234567: Novel kinase inhibitors for oncology", "patent", "PDF"),
    ("Protocol PR-2025-041: In-vivo PK study design", "protocol", "DOCX"),
    ("ELN Export: Compound library screening batch 47", "eln_export", "JSON"),
    ("LIMS Export: Biomarker panel assay results", "lims_export", "CSV"),
    ("Omics dataset: RNA-seq differential expression GSE198234", "omics_dataset", "CSV"),
    ("Regulatory guidance: ICH M7(R2) mutagenic impurities", "regulatory_document", "PDF"),
    ("Literature review: EGFR pathway in NSCLC", "research_paper", "PDF"),
    ("Toxicology report: 28-day repeat dose study SN-1923", "study_report", "PDF"),
]

ENTITY_TYPES = [
    "Gene", "Protein", "Disease", "Target", "Biomarker", "Compound", "Molecule",
    "Assay", "Pathway", "Study", "Protocol", "Experiment", "Result",
    "Toxicity signal", "ADMET attribute", "Formulation", "Manufacturing process", "Regulatory requirement",
]

ENTITY_SAMPLES = [
    ("JAK1", "Gene"), ("JAK2", "Gene"), ("EGFR", "Protein"), ("Rheumatoid Arthritis", "Disease"),
    ("NSCLC", "Disease"), ("SN-2847", "Compound"), ("SN-1923", "Compound"), ("Imatinib", "Compound"),
    ("CRP", "Biomarker"), ("PD-L1", "Biomarker"), ("JAK-STAT Pathway", "Pathway"), ("EGFR Signaling", "Pathway"),
    ("Phase II RA Study", "Study"), ("28-day Tox Study", "Study"), ("PK Study PR-2025-041", "Protocol"),
    ("IC50 Kinase Panel", "Assay"), ("hERG Binding Assay", "Assay"), ("LogP", "ADMET attribute"),
    ("hERG IC50", "ADMET attribute"), ("Oral Formulation F1", "Formulation"), ("Tableting Process P3", "Manufacturing process"),
    ("ICH M7 Compliance", "Regulatory requirement"), ("Cardiotoxicity Signal", "Toxicity signal"),
    ("BRAF V600E", "Target"), ("PD-1", "Target"), ("Aspirin", "Molecule"), ("Metformin", "Molecule"),
]

RELATIONSHIP_TYPES = [
    ("Gene", "ASSOCIATED_WITH", "Disease"),
    ("Protein", "EXPRESSED_IN", "Target"),
    ("Compound", "BINDS_TO", "Target"),
    ("Compound", "HAS_ADMET_PROPERTY", "ADMET attribute"),
    ("Target", "INVOLVED_IN", "Pathway"),
    ("Biomarker", "INDICATES", "Disease"),
    ("Study", "TESTS", "Compound"),
    ("Experiment", "PRODUCES", "Result"),
    ("Protocol", "DEFINES", "Experiment"),
    ("Formulation", "SUPPORTS", "Compound"),
]
